targets:
  $default:
    builders:
      build_web_compilers:entrypoint:
        generate_for:
        - lib/**html.dart
        - web/**.dart
        options:
          compiler: dart2js
          dart2js_args:
          - --csp
